api_version = "2026-01"
uid = "587ca6e1-07e6-4034-87ee-b38b02cfe853"

[[extensions]]
name = "t:name"
handle = "pick-your-own-discount"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  handle = "pick-your-own-discount-ui"
  enable_create = true
